insert into address (id, street, city, state, country, zipcode, profileID) values (1, '671 Truax Center', 'Valdosta', 'Georgia', 'United States', '31605', 1);
insert into address (id, street, city, state, country, zipcode, profileID) values (2, '776 Del Sol Point', 'Kansas City', 'Missouri', 'United States', '64199', 2);
insert into address (id, street, city, state, country, zipcode, profileID) values (3, '27 Nancy Plaza', 'Young America', 'Minnesota', 'United States', '55551', 3);
insert into address (id, street, city, state, country, zipcode, profileID) values (4, '48 Warner Place', 'Daytona Beach', 'Florida', 'United States', '32123', 4);
insert into address (id, street, city, state, country, zipcode, profileID) values (5, '42567 Roth Place', 'Bradenton', 'Florida', 'United States', '34205', 5);
insert into address (id, street, city, state, country, zipcode, profileID) values (6, '589 High Crossing Drive', 'Boston', 'Massachusetts', 'United States', '02114', 6);
insert into address (id, street, city, state, country, zipcode, profileID) values (7, '15 Garrison Circle', 'Dallas', 'Texas', 'United States', '75310', 7);
insert into address (id, street, city, state, country, zipcode, profileID) values (8, '1 Claremont Lane', 'Birmingham', 'Alabama', 'United States', '35295', 8);
insert into address (id, street, city, state, country, zipcode, profileID) values (9, '042 Russell Road', 'Boston', 'Massachusetts', 'United States', '02216', 9);
insert into address (id, street, city, state, country, zipcode, profileID) values (10, '40286 Springs Crossing', 'Clearwater', 'Florida', 'United States', '33763', 10);
insert into address (id, street, city, state, country, zipcode, profileID) values (11, '683 Marquette Center', 'Denver', 'Colorado', 'United States', '80223', 11);
insert into address (id, street, city, state, country, zipcode, profileID) values (12, '5381 Morningstar Trail', 'Bethesda', 'Maryland', 'United States', '20816', 12);
insert into address (id, street, city, state, country, zipcode, profileID) values (13, '259 Lunder Center', 'Louisville', 'Kentucky', 'United States', '40210', 13);
insert into address (id, street, city, state, country, zipcode, profileID) values (14, '6 Westend Circle', 'Atlanta', 'Georgia', 'United States', '31119', 14);
insert into address (id, street, city, state, country, zipcode, profileID) values (15, '13654 Ilene Center', 'Merrifield', 'Virginia', 'United States', '22119', 15);
insert into address (id, street, city, state, country, zipcode, profileID) values (16, '1970 Crownhardt Place', 'Washington', 'District of Columbia', 'United States', '20591', 16);
insert into address (id, street, city, state, country, zipcode, profileID) values (17, '705 Sycamore Drive', 'Greenville', 'South Carolina', 'United States', '29615', 17);
insert into address (id, street, city, state, country, zipcode, profileID) values (18, '09950 Thackeray Center', 'San Jose', 'California', 'United States', '95160', 18);
insert into address (id, street, city, state, country, zipcode, profileID) values (19, '35414 Debs Park', 'Gainesville', 'Florida', 'United States', '32627', 19);
insert into address (id, street, city, state, country, zipcode, profileID) values (20, '84482 Main Court', 'Sandy', 'Utah', 'United States', '84093', 20);
insert into address (id, street, city, state, country, zipcode, profileID) values (21, '57732 Mallard Pass', 'Evansville', 'Indiana', 'United States', '47732', 21);
insert into address (id, street, city, state, country, zipcode, profileID) values (22, '00 Stang Junction', 'Lehigh Acres', 'Florida', 'United States', '33972', 22);
insert into address (id, street, city, state, country, zipcode, profileID) values (23, '8 Haas Circle', 'Houston', 'Texas', 'United States', '77245', 23);
insert into address (id, street, city, state, country, zipcode, profileID) values (24, '62 Service Circle', 'Canton', 'Ohio', 'United States', '44720', 24);
insert into address (id, street, city, state, country, zipcode, profileID) values (25, '40 Morrow Pass', 'Atlanta', 'Georgia', 'United States', '31136', 25);
insert into address (id, street, city, state, country, zipcode, profileID) values (26, '99687 Sunfield Pass', 'Washington', 'District of Columbia', 'United States', '20525', 26);
insert into address (id, street, city, state, country, zipcode, profileID) values (27, '975 Cody Alley', 'Oakland', 'California', 'United States', '94627', 27);
insert into address (id, street, city, state, country, zipcode, profileID) values (28, '6 Iowa Place', 'Chattanooga', 'Tennessee', 'United States', '37450', 28);
insert into address (id, street, city, state, country, zipcode, profileID) values (29, '7 Sutteridge Junction', 'Lynchburg', 'Virginia', 'United States', '24503', 29);
insert into address (id, street, city, state, country, zipcode, profileID) values (30, '44518 Mesta Crossing', 'El Paso', 'Texas', 'United States', '88569', 30);
insert into address (id, street, city, state, country, zipcode, profileID) values (31, '4 Harbort Parkway', 'Milwaukee', 'Wisconsin', 'United States', '53225', 31);
insert into address (id, street, city, state, country, zipcode, profileID) values (32, '1177 Pearson Drive', 'Colorado Springs', 'Colorado', 'United States', '80940', 32);
insert into address (id, street, city, state, country, zipcode, profileID) values (33, '90405 East Lane', 'Los Angeles', 'California', 'United States', '90101', 33);
insert into address (id, street, city, state, country, zipcode, profileID) values (34, '53243 Superior Point', 'Tyler', 'Texas', 'United States', '75705', 34);
insert into address (id, street, city, state, country, zipcode, profileID) values (35, '787 Dryden Avenue', 'Springfield', 'Illinois', 'United States', '62794', 35);
insert into address (id, street, city, state, country, zipcode, profileID) values (36, '34 Pawling Park', 'Inglewood', 'California', 'United States', '90305', 36);
insert into address (id, street, city, state, country, zipcode, profileID) values (37, '8 Texas Park', 'Dallas', 'Texas', 'United States', '75277', 37);
insert into address (id, street, city, state, country, zipcode, profileID) values (38, '89 Bashford Junction', 'Fresno', 'California', 'United States', '93773', 38);
insert into address (id, street, city, state, country, zipcode, profileID) values (39, '07272 Forest Run Terrace', 'Washington', 'District of Columbia', 'United States', '20310', 39);
insert into address (id, street, city, state, country, zipcode, profileID) values (40, '06 Monterey Point', 'Salt Lake City', 'Utah', 'United States', '84105', 40);
insert into address (id, street, city, state, country, zipcode, profileID) values (41, '8 Hanover Drive', 'Sacramento', 'California', 'United States', '95865', 41);
insert into address (id, street, city, state, country, zipcode, profileID) values (42, '45039 Maryland Alley', 'Bakersfield', 'California', 'United States', '93399', 42);
insert into address (id, street, city, state, country, zipcode, profileID) values (43, '5 Duke Hill', 'Dallas', 'Texas', 'United States', '75387', 43);
insert into address (id, street, city, state, country, zipcode, profileID) values (44, '44663 Nobel Alley', 'Charlotte', 'North Carolina', 'United States', '28230', 44);
insert into address (id, street, city, state, country, zipcode, profileID) values (45, '8 Tennessee Road', 'Kansas City', 'Missouri', 'United States', '64144', 45);
insert into address (id, street, city, state, country, zipcode, profileID) values (46, '66 Novick Crossing', 'Chicago', 'Illinois', 'United States', '60674', 46);
insert into address (id, street, city, state, country, zipcode, profileID) values (47, '4420 Kingsford Plaza', 'Memphis', 'Tennessee', 'United States', '38126', 47);
insert into address (id, street, city, state, country, zipcode, profileID) values (48, '86744 Sloan Place', 'Huntsville', 'Alabama', 'United States', '35815', 48);
insert into address (id, street, city, state, country, zipcode, profileID) values (49, '39631 International Way', 'Syracuse', 'New York', 'United States', '13224', 49);
insert into address (id, street, city, state, country, zipcode, profileID) values (50, '0 Golf Center', 'Nashville', 'Tennessee', 'United States', '37235', 50);
insert into address (id, street, city, state, country, zipcode, profileID) values (51, '2544 Buena Vista Lane', 'Burbank', 'California', 'United States', '91505', 51);
insert into address (id, street, city, state, country, zipcode, profileID) values (52, '63 Dwight Parkway', 'Brooklyn', 'New York', 'United States', '11225', 52);
insert into address (id, street, city, state, country, zipcode, profileID) values (53, '224 Debra Park', 'Atlanta', 'Georgia', 'United States', '30323', 53);
insert into address (id, street, city, state, country, zipcode, profileID) values (54, '85240 Dexter Alley', 'Houston', 'Texas', 'United States', '77223', 54);
insert into address (id, street, city, state, country, zipcode, profileID) values (55, '2 Delladonna Place', 'New Orleans', 'Louisiana', 'United States', '70142', 55);
insert into address (id, street, city, state, country, zipcode, profileID) values (56, '588 Briar Crest Center', 'Charleston', 'West Virginia', 'United States', '25305', 56);
insert into address (id, street, city, state, country, zipcode, profileID) values (57, '32212 Westridge Parkway', 'New Haven', 'Connecticut', 'United States', '06533', 57);
insert into address (id, street, city, state, country, zipcode, profileID) values (58, '12286 Buena Vista Circle', 'Oakland', 'California', 'United States', '94605', 58);
insert into address (id, street, city, state, country, zipcode, profileID) values (59, '6 Jana Way', 'New Orleans', 'Louisiana', 'United States', '70165', 59);
insert into address (id, street, city, state, country, zipcode, profileID) values (60, '8 Atwood Street', 'Washington', 'District of Columbia', 'United States', '20520', 60);
insert into address (id, street, city, state, country, zipcode, profileID) values (61, '57628 Parkside Alley', 'Suffolk', 'Virginia', 'United States', '23436', 61);
insert into address (id, street, city, state, country, zipcode, profileID) values (62, '717 Hazelcrest Pass', 'Southfield', 'Michigan', 'United States', '48076', 62);
insert into address (id, street, city, state, country, zipcode, profileID) values (63, '754 Rusk Terrace', 'Chicago', 'Illinois', 'United States', '60630', 63);
insert into address (id, street, city, state, country, zipcode, profileID) values (64, '67 Cascade Parkway', 'Sparks', 'Nevada', 'United States', '89436', 64);
insert into address (id, street, city, state, country, zipcode, profileID) values (65, '159 Leroy Center', 'Washington', 'District of Columbia', 'United States', '20041', 65);
insert into address (id, street, city, state, country, zipcode, profileID) values (66, '33443 Lien Lane', 'Hartford', 'Connecticut', 'United States', '06183', 66);
insert into address (id, street, city, state, country, zipcode, profileID) values (67, '1128 Jenna Terrace', 'Dallas', 'Texas', 'United States', '75379', 67);
insert into address (id, street, city, state, country, zipcode, profileID) values (68, '059 Kenwood Street', 'Newton', 'Massachusetts', 'United States', '02458', 68);
insert into address (id, street, city, state, country, zipcode, profileID) values (69, '1 Emmet Circle', 'Suffolk', 'Virginia', 'United States', '23436', 69);
insert into address (id, street, city, state, country, zipcode, profileID) values (70, '54768 Delaware Road', 'Tacoma', 'Washington', 'United States', '98405', 70);
insert into address (id, street, city, state, country, zipcode, profileID) values (71, '841 Crownhardt Trail', 'Austin', 'Texas', 'United States', '78710', 71);
insert into address (id, street, city, state, country, zipcode, profileID) values (72, '9 Derek Place', 'Longview', 'Texas', 'United States', '75605', 72);
insert into address (id, street, city, state, country, zipcode, profileID) values (73, '2206 Park Meadow Park', 'Oklahoma City', 'Oklahoma', 'United States', '73152', 73);
insert into address (id, street, city, state, country, zipcode, profileID) values (74, '747 Crescent Oaks Terrace', 'Alexandria', 'Virginia', 'United States', '22333', 74);
insert into address (id, street, city, state, country, zipcode, profileID) values (75, '9 Golf View Place', 'Montgomery', 'Alabama', 'United States', '36119', 75);
insert into address (id, street, city, state, country, zipcode, profileID) values (76, '90 Summer Ridge Street', 'Bradenton', 'Florida', 'United States', '34210', 76);
insert into address (id, street, city, state, country, zipcode, profileID) values (77, '571 Delaware Court', 'El Paso', 'Texas', 'United States', '79994', 77);
insert into address (id, street, city, state, country, zipcode, profileID) values (78, '0502 Waubesa Place', 'Detroit', 'Michigan', 'United States', '48275', 78);
insert into address (id, street, city, state, country, zipcode, profileID) values (79, '47 Spenser Avenue', 'San Diego', 'California', 'United States', '92170', 79);
insert into address (id, street, city, state, country, zipcode, profileID) values (80, '31 Alpine Plaza', 'Cincinnati', 'Ohio', 'United States', '45218', 80);
insert into address (id, street, city, state, country, zipcode, profileID) values (81, '55872 Dorton Pass', 'Portland', 'Oregon', 'United States', '97221', 81);
insert into address (id, street, city, state, country, zipcode, profileID) values (82, '820 Karstens Lane', 'San Antonio', 'Texas', 'United States', '78230', 82);
insert into address (id, street, city, state, country, zipcode, profileID) values (83, '631 Hayes Center', 'Kansas City', 'Missouri', 'United States', '64160', 83);
insert into address (id, street, city, state, country, zipcode, profileID) values (84, '08974 Westend Drive', 'Houston', 'Texas', 'United States', '77055', 84);
insert into address (id, street, city, state, country, zipcode, profileID) values (85, '87066 Caliangt Crossing', 'Southfield', 'Michigan', 'United States', '48076', 85);
insert into address (id, street, city, state, country, zipcode, profileID) values (86, '53 Aberg Place', 'Montgomery', 'Alabama', 'United States', '36195', 86);
insert into address (id, street, city, state, country, zipcode, profileID) values (87, '94490 Hovde Junction', 'Albuquerque', 'New Mexico', 'United States', '87201', 87);
insert into address (id, street, city, state, country, zipcode, profileID) values (88, '3382 Manley Park', 'Palatine', 'Illinois', 'United States', '60078', 88);
insert into address (id, street, city, state, country, zipcode, profileID) values (89, '3 Anniversary Park', 'Reading', 'Pennsylvania', 'United States', '19610', 89);
insert into address (id, street, city, state, country, zipcode, profileID) values (90, '125 School Hill', 'Miami', 'Florida', 'United States', '33190', 90);
insert into address (id, street, city, state, country, zipcode, profileID) values (91, '42 Commercial Drive', 'Raleigh', 'North Carolina', 'United States', '27615', 91);
insert into address (id, street, city, state, country, zipcode, profileID) values (92, '8 Pond Pass', 'Baton Rouge', 'Louisiana', 'United States', '70820', 92);
insert into address (id, street, city, state, country, zipcode, profileID) values (93, '3 Spaight Plaza', 'Chicago', 'Illinois', 'United States', '60641', 93);
insert into address (id, street, city, state, country, zipcode, profileID) values (94, '1922 Autumn Leaf Pass', 'New York City', 'New York', 'United States', '10165', 94);
insert into address (id, street, city, state, country, zipcode, profileID) values (95, '88 3rd Pass', 'Pasadena', 'California', 'United States', '91117', 95);
insert into address (id, street, city, state, country, zipcode, profileID) values (96, '0 Mayer Drive', 'Shreveport', 'Louisiana', 'United States', '71130', 96);
insert into address (id, street, city, state, country, zipcode, profileID) values (97, '9 Packers Court', 'Chula Vista', 'California', 'United States', '91913', 97);
insert into address (id, street, city, state, country, zipcode, profileID) values (98, '209 Knutson Center', 'Mobile', 'Alabama', 'United States', '36689', 98);
insert into address (id, street, city, state, country, zipcode, profileID) values (99, '101 Annamark Junction', 'Johnson City', 'Tennessee', 'United States', '37605', 99);
insert into address (id, street, city, state, country, zipcode, profileID) values (100, '2 Hermina Avenue', 'Olympia', 'Washington', 'United States', '98506', 100);
