insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (1, 'zapatos', 'taco bajo', 'Male', 'L', 'Crimson', 'Japan', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (2, 'campera', 'camisa corta', 'Female', 'XL', 'Aquamarine', 'China', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (3, 'buzo', 'pantalon corto', 'Male', 'XL', 'Teal', 'Russia', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (4, 'pantalon', 'taco bajo', 'Male', 'S', 'Crimson', 'Brazil', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (5, 'pantalon', 'camisa ML', 'Male', '2XL', 'Blue', 'China', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (6, 'zapatos', 'bermuda', 'Male', 'XL', 'Aquamarine', 'Indonesia', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (7, 'buzo', 'camisa corta', 'Female', 'M', 'Indigo', 'China', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (8, 'buzo', 'sandalias', 'Female', 'S', 'Blue', 'Portugal', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (9, 'camisa', 'sandalias', 'Female', 'XL', 'Goldenrod', 'Sweden', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (10, 'campera', 'sandalias', 'Male', '2XL', 'Goldenrod', 'China', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (11, 'zapatos', 'pantalon corto', 'Female', 'XS', 'Purple', 'Philippines', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (12, 'buzo', 'sandalias', 'Female', 'XL', 'Teal', 'Nigeria', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (13, 'buzo', 'taco alto', 'Female', '3XL', 'Fuscia', 'Indonesia', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (14, 'campera', 'pantalon corto', 'Male', 'XL', 'Pink', 'Saint Helena', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (15, 'pantalon', 'pantalon corto', 'Male', 'XL', 'Indigo', 'China', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (16, 'buzo', 'pantalon corto', 'Female', '2XL', 'Mauv', 'Honduras', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (17, 'zapatos', 'pantalon corto', 'Male', '2XL', 'Violet', 'Indonesia', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (18, 'campera', 'pantalon corto', 'Male', '2XL', 'Puce', 'China', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (19, 'buzo', 'taco bajo', 'Female', 'L', 'Turquoise', 'Greece', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (20, 'camisa', 'taco bajo', 'Male', 'S', 'Yellow', 'United States', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (21, 'buzo', 'taco alto', 'Male', '2XL', 'Blue', 'France', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (22, 'camisa', 'camisa corta', 'Male', '2XL', 'Fuscia', 'Greece', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (23, 'camisa', 'camisa corta', 'Female', 'XS', 'Puce', 'China', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (24, 'campera', 'sandalias', 'Male', 'L', 'Violet', 'Indonesia', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (25, 'campera', 'camisa ML', 'Female', 'S', 'Mauv', 'Portugal', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (26, 'camisa', 'bermuda', 'Male', 'XL', 'Puce', 'China', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (27, 'camisa', 'pantalon corto', 'Female', 'S', 'Red', 'Russia', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (28, 'campera', 'bermuda', 'Male', 'XL', 'Orange', 'Canada', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (29, 'camisa', 'taco alto', 'Male', 'L', 'Goldenrod', 'China', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (30, 'pantalon', 'sandalias', 'Male', 'S', 'Khaki', 'Philippines', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (31, 'zapatos', 'pantalon corto', 'Female', 'S', 'Teal', 'Japan', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (32, 'buzo', 'sandalias', 'Female', 'L', 'Puce', 'Indonesia', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (33, 'pantalon', 'sandalias', 'Male', 'L', 'Yellow', 'Russia', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (34, 'campera', 'camisa corta', 'Female', 'XS', 'Aquamarine', 'United States', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (35, 'camisa', 'camisa corta', 'Female', 'XL', 'Khaki', 'Philippines', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (36, 'pantalon', 'bermuda', 'Female', 'XL', 'Red', 'Tunisia', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (37, 'pantalon', 'taco alto', 'Male', '3XL', 'Purple', 'Portugal', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (38, 'campera', 'camisa corta', 'Female', 'M', 'Orange', 'Azerbaijan', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (39, 'pantalon', 'camisa corta', 'Male', 'L', 'Purple', 'France', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (40, 'pantalon', 'camisa ML', 'Male', '2XL', 'Teal', 'Philippines', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (41, 'camisa', 'pantalon corto', 'Male', 'XL', 'Orange', 'Poland', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (42, 'campera', 'taco alto', 'Female', 'S', 'Maroon', 'Russia', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (43, 'pantalon', 'bermuda', 'Male', '3XL', 'Turquoise', 'Russia', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (44, 'buzo', 'taco bajo', 'Female', 'L', 'Red', 'Peru', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (45, 'campera', 'bermuda', 'Male', 'XL', 'Turquoise', 'Micronesia', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (46, 'pantalon', 'camisa ML', 'Male', 'L', 'Crimson', 'Philippines', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (47, 'campera', 'taco alto', 'Female', 'S', 'Teal', 'Philippines', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (48, 'buzo', 'pantalon corto', 'Male', 'XS', 'Khaki', 'Venezuela', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (49, 'buzo', 'sandalias', 'Male', 'L', 'Orange', 'Brazil', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (50, 'pantalon', 'taco bajo', 'Female', 'XS', 'Blue', 'China', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (51, 'buzo', 'sandalias', 'Female', 'M', 'Pink', 'Indonesia', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (52, 'camisa', 'pantalon corto', 'Female', 'M', 'Pink', 'Sweden', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (53, 'pantalon', 'bermuda', 'Male', 'S', 'Indigo', 'Russia', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (54, 'buzo', 'pantalon corto', 'Male', 'M', 'Violet', 'China', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (55, 'pantalon', 'bermuda', 'Male', '3XL', 'Purple', 'China', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (56, 'campera', 'pantalon corto', 'Male', '2XL', 'Aquamarine', 'United States', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (57, 'pantalon', 'bermuda', 'Male', 'XS', 'Indigo', 'Indonesia', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (58, 'buzo', 'taco alto', 'Male', 'XS', 'Turquoise', 'China', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (59, 'zapatos', 'camisa ML', 'Male', '2XL', 'Teal', 'Venezuela', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (60, 'pantalon', 'camisa ML', 'Male', 'M', 'Purple', 'Brazil', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (61, 'pantalon', 'sandalias', 'Male', 'M', 'Khaki', 'Colombia', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (62, 'camisa', 'taco alto', 'Female', 'XS', 'Mauv', 'Brazil', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (63, 'buzo', 'taco alto', 'Male', 'XS', 'Indigo', 'Italy', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (64, 'zapatos', 'taco alto', 'Female', 'S', 'Indigo', 'Latvia', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (65, 'buzo', 'camisa corta', 'Female', '3XL', 'Mauv', 'Peru', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (66, 'buzo', 'camisa corta', 'Male', 'L', 'Violet', 'Indonesia', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (67, 'campera', 'pantalon corto', 'Male', 'XL', 'Khaki', 'Philippines', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (68, 'campera', 'taco alto', 'Female', 'XS', 'Aquamarine', 'France', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (69, 'campera', 'taco alto', 'Female', 'XS', 'Turquoise', 'Philippines', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (70, 'zapatos', 'camisa corta', 'Male', '3XL', 'Maroon', 'China', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (71, 'zapatos', 'camisa corta', 'Male', 'XL', 'Fuscia', 'Philippines', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (72, 'buzo', 'camisa corta', 'Male', '2XL', 'Khaki', 'China', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (73, 'camisa', 'sandalias', 'Female', 'XS', 'Turquoise', 'Peru', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (74, 'zapatos', 'pantalon corto', 'Male', 'L', 'Khaki', 'United States', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (75, 'camisa', 'pantalon corto', 'Female', 'XS', 'Turquoise', 'China', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (76, 'buzo', 'camisa corta', 'Male', 'S', 'Maroon', 'France', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (77, 'buzo', 'sandalias', 'Male', 'S', 'Maroon', 'Russia', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (78, 'zapatos', 'taco alto', 'Male', '3XL', 'Khaki', 'China', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (79, 'buzo', 'taco bajo', 'Female', '3XL', 'Purple', 'Sweden', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (80, 'buzo', 'taco alto', 'Female', 'XL', 'Maroon', 'Senegal', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (81, 'buzo', 'bermuda', 'Female', 'S', 'Teal', 'Denmark', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (82, 'zapatos', 'camisa corta', 'Male', '3XL', 'Purple', 'Greece', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (83, 'pantalon', 'bermuda', 'Male', '3XL', 'Aquamarine', 'Russia', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (84, 'pantalon', 'taco alto', 'Male', 'XS', 'Yellow', 'Sweden', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (85, 'pantalon', 'taco bajo', 'Male', '3XL', 'Mauv', 'Nigeria', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (86, 'pantalon', 'taco bajo', 'Male', 'XS', 'Crimson', 'Ireland', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (87, 'camisa', 'taco bajo', 'Male', 'S', 'Green', 'Philippines', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (88, 'camisa', 'pantalon corto', 'Male', 'S', 'Purple', 'Argentina', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (89, 'camisa', 'taco bajo', 'Female', 'S', 'Crimson', 'Ireland', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (90, 'buzo', 'taco bajo', 'Female', 'XL', 'Crimson', 'China', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (91, 'zapatos', 'camisa ML', 'Female', 'S', 'Khaki', 'Indonesia', 'Nuevo', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (92, 'buzo', 'camisa ML', 'Male', 'XL', 'Fuscia', 'Hungary', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (93, 'zapatos', 'camisa corta', 'Male', 'XS', 'Puce', 'China', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (94, 'pantalon', 'taco bajo', 'Male', '3XL', 'Orange', 'Indonesia', 'Usado', 'Tiene algunas cosas');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (95, 'zapatos', 'pantalon corto', 'Male', '3XL', 'Khaki', 'Poland', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (96, 'campera', 'bermuda', 'Male', 'S', 'Indigo', 'Portugal', 'Nuevo', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (97, 'pantalon', 'bermuda', 'Male', 'S', 'Goldenrod', 'Russia', 'Nuevo', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (98, 'zapatos', 'sandalias', 'Male', 'XL', 'Violet', 'France', 'Usado', 'Impecable');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (99, 'zapatos', 'camisa corta', 'Male', '3XL', 'Crimson', 'China', 'Usado', 'Con algo de uso');
insert into variant (id, type, subtype, gender, size, color, brand, usestate, quality) values (100, 'buzo', 'sandalias', 'Female', 'S', 'Pink', 'Russia', 'Usado', 'Con algo de uso');
